# Generated by Django 4.1.4 on 2022-12-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_contact_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.CharField(max_length=50)),
                ('fr', models.CharField(max_length=10)),
                ('temp', models.IntegerField(null=True)),
                ('pa', models.CharField(max_length=50)),
            ],
        ),
    ]
